/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Catppuccin Mocha palette (Dark mode)
        'ctp-d-rosewater': '#f5e0dc',
        'ctp-d-flamingo': '#f2cdcd',
        'ctp-d-pink': '#f5c2e7',
        'ctp-d-mauve': '#cba6f7',
        'ctp-d-red': '#f38ba8',
        'ctp-d-maroon': '#eba0ac',
        'ctp-d-peach': '#fab387',
        'ctp-d-yellow': '#f9e2af',
        'ctp-d-green': '#a6e3a1',
        'ctp-d-teal': '#94e2d5',
        'ctp-d-sky': '#89dceb',
        'ctp-d-sapphire': '#74c7ec',
        'ctp-d-blue': '#89b4fa',
        'ctp-d-lavender': '#b4befe',
        'ctp-d-text': '#cdd6f4',
        'ctp-d-subtext1': '#bac2de',
        'ctp-d-subtext0': '#a6adc8',
        'ctp-d-overlay2': '#9399b2',
        'ctp-d-overlay1': '#7f849c',
        'ctp-d-overlay0': '#6c7086',
        'ctp-d-surface2': '#585b70',
        'ctp-d-surface1': '#45475a',
        'ctp-d-surface0': '#313244',
        'ctp-d-base': '#1e1e2e',
        'ctp-d-mantle': '#181825',
        'ctp-d-crust': '#11111b',

        // Catppuccin Latte palette (Light mode)
        'ctp-l-rosewater': '#dc8a78',
        'ctp-l-flamingo': '#dd7878',
        'ctp-l-pink': '#ea76cb',
        'ctp-l-mauve': '#8839ef',
        'ctp-l-red': '#d20f39',
        'ctp-l-maroon': '#e64553',
        'ctp-l-peach': '#fe640b',
        'ctp-l-yellow': '#df8e1d',
        'ctp-l-green': '#40a02b',
        'ctp-l-teal': '#179299',
        'ctp-l-sky': '#04a5e5',
        'ctp-l-sapphire': '#209fb5',
        'ctp-l-blue': '#1e66f5',
        'ctp-l-lavender': '#7287fd',
        'ctp-l-text': '#4c4f69',
        'ctp-l-subtext1': '#5c5f77',
        'ctp-l-subtext0': '#6c6f85',
        'ctp-l-overlay2': '#7c7f93',
        'ctp-l-overlay1': '#8c8fa1',
        'ctp-l-overlay0': '#9ca0b0',
        'ctp-l-surface2': '#acb0be',
        'ctp-l-surface1': '#bcc0cc',
        'ctp-l-surface0': '#ccd0da',
        'ctp-l-base': '#eff1f5',
        'ctp-l-mantle': '#e6e9ef',
        'ctp-l-crust': '#dce0e8',
      },
    },
  },
  plugins: [],
};